#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    project-tabletop-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^project-tabletop\.ddev\.site$`)
      
      service: "project-tabletop-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "project-tabletop-redirectHttps"
    project-tabletop-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^project-tabletop\.ddev\.site$`)
      
      service: "project-tabletop-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "project-tabletop-redirectHttps"
    project-tabletop-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^project-tabletop\.ddev\.site$`)
      
      service: "project-tabletop-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "project-tabletop-redirectHttps"
    
    
    
    project-tabletop-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^project-tabletop\.ddev\.site$`)
      
      service: "project-tabletop-web-80"
      ruleSyntax: v3
      
      tls: true
      
    project-tabletop-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^project-tabletop\.ddev\.site$`)
      
      service: "project-tabletop-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    
    project-tabletop-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^project-tabletop\.ddev\.site$`)
      
      service: "project-tabletop-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    project-tabletop-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    project-tabletop-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-project-tabletop-web:80
        
    project-tabletop-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-project-tabletop-web:8025
        
    
    
    project-tabletop-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-project-tabletop-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/project-tabletop.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/project-tabletop.key